server:
  port: 8081

app:
  url: http://localhost:8081/
  log-path: logs

logging:
  level:
    pl.dgrecki.logs.RequestLoggingFilter: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:1011/auth_db
    username: auth_user
    password: 123 # It will eventually be moved to .env
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 50
      buffer-memory: 33554432
      compression-type: gzip
    properties:
      delivery.timeout.ms: 30000
      request.timeout.ms: 10000
      max.block.ms: 5000
    topics:
      user-registration: mail.registration.user
    poll-interval-ms: 5000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

jwt:
  secret: superDlugiKluczMinimum32ZnakiTutaj

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
