CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS cinema;

CREATE USER auth_user WITH PASSWORD '123';
CREATE USER cinema_user WITH PASSWORD '123';


GRANT USAGE, CREATE ON SCHEMA auth TO auth_user;
GRANT USAGE, CREATE ON SCHEMA cinema TO cinema_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO auth_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cinema TO cinema_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO auth_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO auth_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cinema GRANT ALL ON TABLES TO cinema_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cinema GRANT ALL ON SEQUENCES TO cinema_user;

GRANT ALL PRIVILEGES ON SCHEMA auth TO root;
GRANT ALL PRIVILEGES ON SCHEMA cinema TO root;
