server:
  port: 8082

app:
  log-path: logs

spring:
  datasource:
    url: jdbc:postgresql://localhost:1012/mail_db
    username: mail_user
    password: 123 # It will eventually be moved to .env

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mail-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    sender: no-reply@cinema-service.com
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

kafka:
  topics:
    user-registration: mail.registration.user
    user-registration-dlq: mail.registration.user.dlq

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always