server:
  port: 8082

app:
  log-path: logs

spring:
  datasource:
    url: jdbc:postgresql://localhost:1012/mail_db
    username: mail_user
    password: 123 # It will eventually be moved to .env
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mail-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
      session-timeout-ms: 15000
      heartbeat-interval-ms: 3000
      isolation-level: read_committed

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  mail:
    sender: no-reply@cinema-service.com
    host: localhost
    port: 1025

kafka:
  topics:
    user-registration: mail.registration.user
    ticket-generated: ticket.generated
    ticket-generated-dlq: ticket.generated.dlq
    user-registration-dlq: mail.registration.user.dlq

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always