server:
  port: 8080

app:
  log-path: logs

logging:
  level:
    pl.dgrecki.logs.RequestLoggingFilter: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:1010/cinema_db
    username: cinema_user
    password: 123 # It will eventually be moved to .env
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      retries: 3
      compression-type: gzip
    properties:
      delivery.timeout.ms: 30000
      request.timeout.ms: 10000
      max.block.ms: 5000
    topics:
      ticket-generated: ticket.generated
    poll-interval-ms: 5000
    hmac-secret: kafka-shared-hmac-secret-min-32-chars # It will eventually be moved to .env

jwt:
  secret: superDlugiKluczMinimum32ZnakiTutaj

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always

scheduler:
  reservation:
    update:
      limit: 100
      delay-ms: 60000
    delete:
      older-than-days: 1
      limit: 100
      delay-ms: 60000
  basket:
    delete:
      older-than-days: 1
      limit: 100
      delay-ms: 60000
  ticket-pdf:
    limit: 50
    delay-ms: 10000
    max-attempts: 3
  ticket-refund:
    delay-ms: 30000
    max-attempts: 3

ticket:
  storage:
    type: local
    local:
      directory: ./ticket-pdfs
  download:
    signing-secret: secureRandomKeyForTicketsPdfDownload
    base-url: http://localhost:8080

poster:
  storage:
    type: local
    local:
      directory: ./posters

auth-service:
  url: http://localhost:8081
  name: cinema-service
  client-secret: cinema-service-secret # It will eventually be moved to .env

payment-provider:
  attempts-limit: 3
  sandbox:
    url: http://localhost:1080

