version: '3.8'

services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cinema-network
    restart: always

networks:
  cinema-network:
    external: true
