version: '3.8'

services:
  mail-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mail-service
    container_name: mail-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mail-db:5432/${MAIL_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${MAIL_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MAIL_DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_MAIL_HOST: mailpit
    networks:
      - cinema-network

networks:
  cinema-network:
    external: true
